/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ActivateTenantRequest {
    /**
    * The full name of your company.
    */
    'companyName': string;
    /**
    * The first line of the address for your company.
    */
    'companyAddress': string;
    /**
    * The city in which the address is located.
    */
    'companyCity': string;
    /**
    * The postal code for the address.
    */
    'companyPostalCode': string;
    /**
    * The country in which the address is located. This should be given as an ISO 3361-1 country code (two letter abbreviation).
    */
    'companyCountry': string;
    /**
    * Your company's organization number.
    */
    'companyOrgNumber': string;
    /**
    * A value added tax identification number, identifier used in many countries, including the countries of the European Union, for value added tax purposes.
    */
    'companyVATNumber': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyAddress",
            "baseName": "companyAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyCity",
            "baseName": "companyCity",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyPostalCode",
            "baseName": "companyPostalCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyCountry",
            "baseName": "companyCountry",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyOrgNumber",
            "baseName": "companyOrgNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "companyVATNumber",
            "baseName": "companyVATNumber",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ActivateTenantRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

