/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateTenantRequest {
    /**
    * The name of the tenant should preferably be the name of your organization/company. Does not need to be but your end users will see this name.
    */
    'tenantName': string;
    /**
    * Email to the person that will be tenant admin.
    */
    'adminEmail': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tenantName",
            "baseName": "tenantName",
            "type": "string",
            "format": ""
        },
        {
            "name": "adminEmail",
            "baseName": "adminEmail",
            "type": "string",
            "format": "email"
        }    ];

    static getAttributeTypeMap() {
        return CreateTenantRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

