/**
 * Lagrello API
 * API specification for Lagrello, a simple to use authentication service
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@lagrello.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TenantCompanyInfo {
    /**
    * The full name of your company.
    */
    'name': string;
    /**
    * The first line of the address for your company.
    */
    'address': string;
    /**
    * The city in which the address is located.
    */
    'city': string;
    /**
    * The postal code for the address.
    */
    'postalCode': string;
    /**
    * The country in which the address is located. This should be given as an ISO 3361-1 country code (two letter abbreviation).
    */
    'country': string;
    /**
    * Your company's organization number.
    */
    'orgNumber': string;
    /**
    * A value added tax identification number, identifier used in many countries, including the countries of the European Union, for value added tax purposes.
    */
    'vATNumber': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "Name",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "Address",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "City",
            "type": "string",
            "format": ""
        },
        {
            "name": "postalCode",
            "baseName": "PostalCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "country",
            "baseName": "Country",
            "type": "string",
            "format": ""
        },
        {
            "name": "orgNumber",
            "baseName": "OrgNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "vATNumber",
            "baseName": "VATNumber",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TenantCompanyInfo.attributeTypeMap;
    }
    
    public constructor() {
    }
}

